### ISSUE TITLE
got error with mirror function on edision NERSC

### ISSUE THREAD

**Issue by guotsuan** [rainwoodman/python-mpi-bcast#3]
Hi,

When I use the python-mpi-bcast on editon.nersc.org (I think it is newest version) with command

> mirror /global/u2/g/guotsuan/projs/decals/imaginglss imaginglss scripts
> I got errors:
> archive_read_open_filename() failed: Unrecognized archive format
> ....
> srun: error: nid00280: task 14: Exited with exit code 226
> ...
> rm: cannot remove `/global/u2/g/guotsuan/projs/decals/imaginglss': Is a directory
> rm: cannot remove`/global/u2/g/guotsuan/projs/decals/imaginglss/mask_test': Is a directory
> rm: cannot remove `/global/u2/g/guotsuan/projs/decals/imaginglss/mask_test': Is a directory
> ...

This command worked before. I'm wondering if it use the command mirror wrong? Thanks

**Comment by rainwoodman** [comment]
There is probably a message like this in the log:

```
    echo "------------------------------------------"
    echo "( $DIR/ $* ) has a total size of $total MiB. Cowardly refusing to create such a large bundle."
    echo "In $DIR "
    du -sh $*
    echo "Possible solutions: "
    echo "1. Remove unnecessary data files in the directory. This is the usual solution. "
    echo "   Refer to the output of command 'du -sh $DIR' "
    echo "2. Properly package the installable package with the bundle command. Do not use the mirror command."
    echo "   The package must conform to the pip packaging standard, with a setup.py file. "
    echo "------------------------------------------"
    ) 1>&2
```

The new version of mirror refuses to mirror a directory bigger than 50 MB because it is very inefficient -- occaisionally takes forever. 

Did you have large left over data files in the script/ and imaginglss/ directory? If so please remove them from the source code directories.

I am not very sure what is triggering the rm lines. Did you have rm in your job script? 
Can you add 'set -x' to the job script and see what happens?

**Comment by rainwoodman** [comment]
I found a bug in the new tar-dir.sh script. It should have been fixed now. Let me know if the problem persists.

**Comment by guotsuan** [comment]
Thank you very much.  The problem has gone now.
